name: linguaanimae
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - regex
      - requests
      - beautifulsoup4
      - soupsieve
      - python-dateutil
      - pytz
      - matplotlib
      - seaborn
      - tqdm
      - altair
      - pydeck
      - transformers
      - sentence-transformers
      - tokenizers
      - torch
      - torchvision
      - torchaudio
      - protobuf
      - pyarrow
      - pyyaml
      - typing-extensions
      - streamlit
      - deep-translator
      - qdrant-client
